# Macro file
#
# % detector.mac
#
#/detector/arraySize
#       --/detectorX
#       --/detectorY
#       --/detectorZ
#       --/moduleDistance
#       --/gdFilmThickness
#       --/update          ### DONOT USE!! BUG WITH SENSITIVE DETECTOR ###
### Use this command before /run/initialize ###
#
/detector/arraySize 4
/detector/detectorX 10 cm
/detector/detectorX 10 cm
/detector/detectorZ 100 cm
/detector/moduleDistance 2 cm
/detector/gdFilmThickness 30 um
