# Macro file
#
# % neutrino.mac
#
#/source/type              ## Cs137/Co60/Na22/Cs137g/Co60g/Am-Be-n/GUN with position CENTER/EDGE;
                           ## GUN with position INSIDE or COMMAND (means defined by UI command);
                           ## He8; Li9; NEUTRINO; MUON; COSMICNEUTRON; CRY (Linux only); GPS
                           ## Position, momentum, particle etc. must be defined with source GPS.
#     --/spectra           ## Spectra for neutron and positron. See spectra directory.
#     --/position          ## Position for Cs137/Co60/Na22/Cs137g/Co60g/Am-Be-n
#                          ## Direction must be defined for GUN with position CENTER/EDGE.
#                          ## Direction and position must be defined for GUN with position COMMAND.
#                          ## Direction is isotropic for GUN with position INSIDE.
#     --/neutrinoPosition  ## Position for NEUTRINO, two positive integers [0 - size*size, 0 - 5]
#                          ## First integer: Position in the detector array, size*size means random.
#                          ## Second integer: Position in the detector module, 5 means random.
#                          ## Second integer is valid only when arrayPosition < size*size.
### Use this command after /run/initialize ###
#
/source/type NEUTRINO
/source/spectra IBDNeutron.spec IBDPositron.spec
/source/neutrinoPosition 16 5

