# Macro file
# 
# To be run preferably in batch, without graphics:
# % run.mac
#
/run/numberOfThreads 8
/run/initialize
#
/control/verbose 2
/run/verbose 2
/event/verbose 0
/tracking/verbose 0
#
# Source setting, after /run/initialize
/control/loop neutrino.mac id 0 10
#/control/loop cry.mac id 0 10
#/control/foreach calibration.mac sType "Cs137 Co60"
#/control/foreach nCap.mac Ekin "0.0000253 1. 5."
#/control/loop nCap.mac Ekin 10. 50. 5
#/control/foreach He8Li9.mac sType "He8 Li9"
